try to fix vagrant setup

diff --git a/deploy/templates/postinst.erb b/deploy/templates/postinst.erb
--- a/deploy/templates/postinst.erb
+++ b/deploy/templates/postinst.erb
@@ -13,6 +13,13 @@ if ! gem list bundler -i > /dev/null ; then
   gem install bundler --no-ri --no-rdoc
 fi
 
+# if ! gem list passenger -i -v "4.0.29" > /dev/null ; then
+#   echo "gem passenger not found, installing ..."
+#   gem install passenger -v "4.0.29" --no-ri --no-rdoc
+#   passenger-install-apache2-module -a
+#   passenger-install-apache2-module --snippet > /etc/apache2/mods-available/passenger.load
+#   touch /etc/apache2/mods-available/passenger.conf
+# fi
 a2enmod passenger
 service apache2 restart
 
@@ -23,7 +30,7 @@ if ! [ -e /etc/apache2/sites-enabled/kor ] ; then
 fi
 
 mkdir -p /opt/kor/shared
-chown -R kor. /opt/kor
+chown -R kor. /opt/kor/shared /opt/kor/current
 
 cd /opt/kor/current
 echo "Installing gems with bundler (this may take a few minutes) ..."
